### PR TITLE
Update job status field

### PR DESCRIPTION
**Pull request by v4l3r10**
ref #19

### CODE REVIEW

**Comment by LewisJEllis** [comment]
Can you make sure `grunt test` passes? Happy to look at this, but right now Travis CI is failing.

**Comment by thelinuxlich** [comment]
+1

**Comment by Ruskiz** [comment]
+1

**Comment by v4l3r10** [comment]
@LewisJEllis travis now is Ok ;)

**Comment by LewisJEllis** [comment]
Looks good, thanks!

**Pull request merged**
