### PR TITLE
Switch from JSON.parse/stringify to msgpack-lite

### PR DESCRIPTION
**Pull request by v4l3r10**
updated dependencies: switch to last node redis and last dev tool.
switch to msgpack-lite, best performance and memory use (Reduces ~25% the size of job data).
fixed some tests for new redis/msgpack  and eslint

### CODE REVIEW

**Comment by thelinuxlich** [comment]
Out of curiosity, why the switch to msgpack? Is it better, in this use case, to trade CPU for bandwidth?

**Comment by matteocontrini** [comment]
Also, this would be a breaking change with no compatibility with the data already stored in Redis

**Comment by v4l3r10** [comment]
@thelinuxlich we lose ~10% cpu performance for a reduction of    ~20%/~30% of memory use... and the time for transfer data from redis to node memory... i need to do some benchmark but i think that, overall, Cpu time is the same.

@matteocontrini u never restarted / flushed ur redis database? u leave all data for all time in memory? In my use case i flush redis db every night, so no problem for me.

**Comment by matteocontrini** [comment]
@v4l3r10 what? I have the queue of jobs in the database, why should I even flush it? Data is there to be processed. If this update goes out, jobs that are still to be processed in the database will make the app crash.

**Comment by v4l3r10** [comment]
@matteocontrini REDIS is an in memory database, is not made for  fault-tolerance but only for performance .  I think u need to change Paradigm for your project.

**Comment by matteocontrini** [comment]
Sorry but intentionally flushing the database data is not what I call "fault tolerance" :P

**Comment by v4l3r10** [comment]
No MSGPACK
Ran 10000 jobs through Bee-Queue with concurrency 1 in 4862 ms         3.72MB 
Ran 10000 jobs through Bee-Queue with concurrency 5 in 3496 ms         3.78MB
Ran 10000 jobs through Bee-Queue with concurrency 20 in 3377 ms        3.79MB
Ran 10000 jobs through Bee-Queue with concurrency 50 in 3183 ms        3.79MB
                                                                      
with MSGPACK                                                          
Ran 10000 jobs through Bee-Queue with concurrency 1 in 5502 ms   113%  3.58MB  96%
Ran 10000 jobs through Bee-Queue with concurrency 5 in 4037 ms   115%  3.58MB  94%
Ran 10000 jobs through Bee-Queue with concurrency 20 in 3762 ms  111%  3.64MB  96%
Ran 10000 jobs through Bee-Queue with concurrency 50 in 3627 ms  113%  3.64MB  96%

**Comment by thelinuxlich** [comment]
Sorry, but I fail to see the usefulness of this change in this use case

**Comment by v4l3r10** [comment]
@thelinuxlich  try to work with DateTime Obj with TimeZone.

**Comment by thelinuxlich** [comment]
Care to explain?

**Comment by v4l3r10** [comment]
Try to store a DateTime Obj with timezone in job data. It lose timezone reference during isostring translation. With msgpack i can  preserve all dateTime Obj structure. It's not translated to String, but remain js Obj.

**Pull request closed without merging**
